// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/davidbz/calcifer/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockCostCalculator is an autogenerated mock type for the CostCalculator type
type MockCostCalculator struct {
	mock.Mock
}

type MockCostCalculator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCostCalculator) EXPECT() *MockCostCalculator_Expecter {
	return &MockCostCalculator_Expecter{mock: &_m.Mock}
}

// Calculate provides a mock function with given fields: ctx, model, usage
func (_m *MockCostCalculator) Calculate(ctx context.Context, model string, usage domain.Usage) (float64, error) {
	ret := _m.Called(ctx, model, usage)

	if len(ret) == 0 {
		panic("no return value specified for Calculate")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Usage) (float64, error)); ok {
		return rf(ctx, model, usage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Usage) float64); ok {
		r0 = rf(ctx, model, usage)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.Usage) error); ok {
		r1 = rf(ctx, model, usage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCostCalculator_Calculate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Calculate'
type MockCostCalculator_Calculate_Call struct {
	*mock.Call
}

// Calculate is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
//   - usage domain.Usage
func (_e *MockCostCalculator_Expecter) Calculate(ctx interface{}, model interface{}, usage interface{}) *MockCostCalculator_Calculate_Call {
	return &MockCostCalculator_Calculate_Call{Call: _e.mock.On("Calculate", ctx, model, usage)}
}

func (_c *MockCostCalculator_Calculate_Call) Run(run func(ctx context.Context, model string, usage domain.Usage)) *MockCostCalculator_Calculate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.Usage))
	})
	return _c
}

func (_c *MockCostCalculator_Calculate_Call) Return(_a0 float64, _a1 error) *MockCostCalculator_Calculate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCostCalculator_Calculate_Call) RunAndReturn(run func(context.Context, string, domain.Usage) (float64, error)) *MockCostCalculator_Calculate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCostCalculator creates a new instance of MockCostCalculator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCostCalculator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCostCalculator {
	mock := &MockCostCalculator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
