// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEmbeddingGenerator is an autogenerated mock type for the EmbeddingGenerator type
type MockEmbeddingGenerator struct {
	mock.Mock
}

type MockEmbeddingGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingGenerator) EXPECT() *MockEmbeddingGenerator_Expecter {
	return &MockEmbeddingGenerator_Expecter{mock: &_m.Mock}
}

// Dimension provides a mock function with no fields
func (_m *MockEmbeddingGenerator) Dimension() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dimension")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockEmbeddingGenerator_Dimension_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dimension'
type MockEmbeddingGenerator_Dimension_Call struct {
	*mock.Call
}

// Dimension is a helper method to define mock.On call
func (_e *MockEmbeddingGenerator_Expecter) Dimension() *MockEmbeddingGenerator_Dimension_Call {
	return &MockEmbeddingGenerator_Dimension_Call{Call: _e.mock.On("Dimension")}
}

func (_c *MockEmbeddingGenerator_Dimension_Call) Run(run func()) *MockEmbeddingGenerator_Dimension_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEmbeddingGenerator_Dimension_Call) Return(_a0 int) *MockEmbeddingGenerator_Dimension_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmbeddingGenerator_Dimension_Call) RunAndReturn(run func() int) *MockEmbeddingGenerator_Dimension_Call {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function with given fields: ctx, text
func (_m *MockEmbeddingGenerator) Generate(ctx context.Context, text string) ([]float64, error) {
	ret := _m.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 []float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]float64, error)); ok {
		return rf(ctx, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []float64); ok {
		r0 = rf(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmbeddingGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockEmbeddingGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockEmbeddingGenerator_Expecter) Generate(ctx interface{}, text interface{}) *MockEmbeddingGenerator_Generate_Call {
	return &MockEmbeddingGenerator_Generate_Call{Call: _e.mock.On("Generate", ctx, text)}
}

func (_c *MockEmbeddingGenerator_Generate_Call) Run(run func(ctx context.Context, text string)) *MockEmbeddingGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEmbeddingGenerator_Generate_Call) Return(_a0 []float64, _a1 error) *MockEmbeddingGenerator_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmbeddingGenerator_Generate_Call) RunAndReturn(run func(context.Context, string) ([]float64, error)) *MockEmbeddingGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockEmbeddingGenerator) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEmbeddingGenerator_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockEmbeddingGenerator_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockEmbeddingGenerator_Expecter) Name() *MockEmbeddingGenerator_Name_Call {
	return &MockEmbeddingGenerator_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockEmbeddingGenerator_Name_Call) Run(run func()) *MockEmbeddingGenerator_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEmbeddingGenerator_Name_Call) Return(_a0 string) *MockEmbeddingGenerator_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmbeddingGenerator_Name_Call) RunAndReturn(run func() string) *MockEmbeddingGenerator_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmbeddingGenerator creates a new instance of MockEmbeddingGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingGenerator {
	mock := &MockEmbeddingGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
