// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/davidbz/calcifer/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockPricingRegistry is an autogenerated mock type for the PricingRegistry type
type MockPricingRegistry struct {
	mock.Mock
}

type MockPricingRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPricingRegistry) EXPECT() *MockPricingRegistry_Expecter {
	return &MockPricingRegistry_Expecter{mock: &_m.Mock}
}

// GetPricing provides a mock function with given fields: ctx, model
func (_m *MockPricingRegistry) GetPricing(ctx context.Context, model string) (domain.PricingConfig, error) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for GetPricing")
	}

	var r0 domain.PricingConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.PricingConfig, error)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.PricingConfig); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Get(0).(domain.PricingConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPricingRegistry_GetPricing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPricing'
type MockPricingRegistry_GetPricing_Call struct {
	*mock.Call
}

// GetPricing is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
func (_e *MockPricingRegistry_Expecter) GetPricing(ctx interface{}, model interface{}) *MockPricingRegistry_GetPricing_Call {
	return &MockPricingRegistry_GetPricing_Call{Call: _e.mock.On("GetPricing", ctx, model)}
}

func (_c *MockPricingRegistry_GetPricing_Call) Run(run func(ctx context.Context, model string)) *MockPricingRegistry_GetPricing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPricingRegistry_GetPricing_Call) Return(_a0 domain.PricingConfig, _a1 error) *MockPricingRegistry_GetPricing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPricingRegistry_GetPricing_Call) RunAndReturn(run func(context.Context, string) (domain.PricingConfig, error)) *MockPricingRegistry_GetPricing_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterPricing provides a mock function with given fields: ctx, model, config
func (_m *MockPricingRegistry) RegisterPricing(ctx context.Context, model string, config domain.PricingConfig) error {
	ret := _m.Called(ctx, model, config)

	if len(ret) == 0 {
		panic("no return value specified for RegisterPricing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.PricingConfig) error); ok {
		r0 = rf(ctx, model, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPricingRegistry_RegisterPricing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterPricing'
type MockPricingRegistry_RegisterPricing_Call struct {
	*mock.Call
}

// RegisterPricing is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
//   - config domain.PricingConfig
func (_e *MockPricingRegistry_Expecter) RegisterPricing(ctx interface{}, model interface{}, config interface{}) *MockPricingRegistry_RegisterPricing_Call {
	return &MockPricingRegistry_RegisterPricing_Call{Call: _e.mock.On("RegisterPricing", ctx, model, config)}
}

func (_c *MockPricingRegistry_RegisterPricing_Call) Run(run func(ctx context.Context, model string, config domain.PricingConfig)) *MockPricingRegistry_RegisterPricing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.PricingConfig))
	})
	return _c
}

func (_c *MockPricingRegistry_RegisterPricing_Call) Return(_a0 error) *MockPricingRegistry_RegisterPricing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPricingRegistry_RegisterPricing_Call) RunAndReturn(run func(context.Context, string, domain.PricingConfig) error) *MockPricingRegistry_RegisterPricing_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPricingRegistry creates a new instance of MockPricingRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPricingRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPricingRegistry {
	mock := &MockPricingRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
