// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/davidbz/calcifer/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: ctx, req
func (_m *MockProvider) Complete(ctx context.Context, req *domain.CompletionRequest) (*domain.CompletionResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 *domain.CompletionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CompletionRequest) (*domain.CompletionResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CompletionRequest) *domain.CompletionResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CompletionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CompletionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockProvider_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.CompletionRequest
func (_e *MockProvider_Expecter) Complete(ctx interface{}, req interface{}) *MockProvider_Complete_Call {
	return &MockProvider_Complete_Call{Call: _e.mock.On("Complete", ctx, req)}
}

func (_c *MockProvider_Complete_Call) Run(run func(ctx context.Context, req *domain.CompletionRequest)) *MockProvider_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.CompletionRequest))
	})
	return _c
}

func (_c *MockProvider_Complete_Call) Return(_a0 *domain.CompletionResponse, _a1 error) *MockProvider_Complete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_Complete_Call) RunAndReturn(run func(context.Context, *domain.CompletionRequest) (*domain.CompletionResponse, error)) *MockProvider_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// IsModelSupported provides a mock function with given fields: ctx, model
func (_m *MockProvider) IsModelSupported(ctx context.Context, model string) bool {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for IsModelSupported")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockProvider_IsModelSupported_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsModelSupported'
type MockProvider_IsModelSupported_Call struct {
	*mock.Call
}

// IsModelSupported is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
func (_e *MockProvider_Expecter) IsModelSupported(ctx interface{}, model interface{}) *MockProvider_IsModelSupported_Call {
	return &MockProvider_IsModelSupported_Call{Call: _e.mock.On("IsModelSupported", ctx, model)}
}

func (_c *MockProvider_IsModelSupported_Call) Run(run func(ctx context.Context, model string)) *MockProvider_IsModelSupported_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProvider_IsModelSupported_Call) Return(_a0 bool) *MockProvider_IsModelSupported_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvider_IsModelSupported_Call) RunAndReturn(run func(context.Context, string) bool) *MockProvider_IsModelSupported_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockProvider) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockProvider_Expecter) Name() *MockProvider_Name_Call {
	return &MockProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockProvider_Name_Call) Run(run func()) *MockProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_Name_Call) Return(_a0 string) *MockProvider_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvider_Name_Call) RunAndReturn(run func() string) *MockProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Stream provides a mock function with given fields: ctx, req
func (_m *MockProvider) Stream(ctx context.Context, req *domain.CompletionRequest) (<-chan domain.StreamChunk, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 <-chan domain.StreamChunk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CompletionRequest) (<-chan domain.StreamChunk, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CompletionRequest) <-chan domain.StreamChunk); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan domain.StreamChunk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CompletionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_Stream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stream'
type MockProvider_Stream_Call struct {
	*mock.Call
}

// Stream is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.CompletionRequest
func (_e *MockProvider_Expecter) Stream(ctx interface{}, req interface{}) *MockProvider_Stream_Call {
	return &MockProvider_Stream_Call{Call: _e.mock.On("Stream", ctx, req)}
}

func (_c *MockProvider_Stream_Call) Run(run func(ctx context.Context, req *domain.CompletionRequest)) *MockProvider_Stream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.CompletionRequest))
	})
	return _c
}

func (_c *MockProvider_Stream_Call) Return(_a0 <-chan domain.StreamChunk, _a1 error) *MockProvider_Stream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_Stream_Call) RunAndReturn(run func(context.Context, *domain.CompletionRequest) (<-chan domain.StreamChunk, error)) *MockProvider_Stream_Call {
	_c.Call.Return(run)
	return _c
}

// SupportedModels provides a mock function with given fields: ctx
func (_m *MockProvider) SupportedModels(ctx context.Context) []string {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SupportedModels")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockProvider_SupportedModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportedModels'
type MockProvider_SupportedModels_Call struct {
	*mock.Call
}

// SupportedModels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) SupportedModels(ctx interface{}) *MockProvider_SupportedModels_Call {
	return &MockProvider_SupportedModels_Call{Call: _e.mock.On("SupportedModels", ctx)}
}

func (_c *MockProvider_SupportedModels_Call) Run(run func(ctx context.Context)) *MockProvider_SupportedModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProvider_SupportedModels_Call) Return(_a0 []string) *MockProvider_SupportedModels_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvider_SupportedModels_Call) RunAndReturn(run func(context.Context) []string) *MockProvider_SupportedModels_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
