// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/davidbz/calcifer/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockProviderRegistry is an autogenerated mock type for the ProviderRegistry type
type MockProviderRegistry struct {
	mock.Mock
}

type MockProviderRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderRegistry) EXPECT() *MockProviderRegistry_Expecter {
	return &MockProviderRegistry_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, providerName
func (_m *MockProviderRegistry) Get(ctx context.Context, providerName string) (domain.Provider, error) {
	ret := _m.Called(ctx, providerName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Provider, error)); ok {
		return rf(ctx, providerName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Provider); ok {
		r0 = rf(ctx, providerName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, providerName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderRegistry_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProviderRegistry_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - providerName string
func (_e *MockProviderRegistry_Expecter) Get(ctx interface{}, providerName interface{}) *MockProviderRegistry_Get_Call {
	return &MockProviderRegistry_Get_Call{Call: _e.mock.On("Get", ctx, providerName)}
}

func (_c *MockProviderRegistry_Get_Call) Run(run func(ctx context.Context, providerName string)) *MockProviderRegistry_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProviderRegistry_Get_Call) Return(_a0 domain.Provider, _a1 error) *MockProviderRegistry_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProviderRegistry_Get_Call) RunAndReturn(run func(context.Context, string) (domain.Provider, error)) *MockProviderRegistry_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByModel provides a mock function with given fields: ctx, model
func (_m *MockProviderRegistry) GetByModel(ctx context.Context, model string) (domain.Provider, error) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for GetByModel")
	}

	var r0 domain.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Provider, error)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Provider); ok {
		r0 = rf(ctx, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderRegistry_GetByModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByModel'
type MockProviderRegistry_GetByModel_Call struct {
	*mock.Call
}

// GetByModel is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
func (_e *MockProviderRegistry_Expecter) GetByModel(ctx interface{}, model interface{}) *MockProviderRegistry_GetByModel_Call {
	return &MockProviderRegistry_GetByModel_Call{Call: _e.mock.On("GetByModel", ctx, model)}
}

func (_c *MockProviderRegistry_GetByModel_Call) Run(run func(ctx context.Context, model string)) *MockProviderRegistry_GetByModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProviderRegistry_GetByModel_Call) Return(_a0 domain.Provider, _a1 error) *MockProviderRegistry_GetByModel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProviderRegistry_GetByModel_Call) RunAndReturn(run func(context.Context, string) (domain.Provider, error)) *MockProviderRegistry_GetByModel_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockProviderRegistry) List(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderRegistry_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockProviderRegistry_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProviderRegistry_Expecter) List(ctx interface{}) *MockProviderRegistry_List_Call {
	return &MockProviderRegistry_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockProviderRegistry_List_Call) Run(run func(ctx context.Context)) *MockProviderRegistry_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProviderRegistry_List_Call) Return(_a0 []string, _a1 error) *MockProviderRegistry_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProviderRegistry_List_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockProviderRegistry_List_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, provider
func (_m *MockProviderRegistry) Register(ctx context.Context, provider domain.Provider) error {
	ret := _m.Called(ctx, provider)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Provider) error); ok {
		r0 = rf(ctx, provider)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProviderRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockProviderRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - provider domain.Provider
func (_e *MockProviderRegistry_Expecter) Register(ctx interface{}, provider interface{}) *MockProviderRegistry_Register_Call {
	return &MockProviderRegistry_Register_Call{Call: _e.mock.On("Register", ctx, provider)}
}

func (_c *MockProviderRegistry_Register_Call) Run(run func(ctx context.Context, provider domain.Provider)) *MockProviderRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Provider))
	})
	return _c
}

func (_c *MockProviderRegistry_Register_Call) Return(_a0 error) *MockProviderRegistry_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProviderRegistry_Register_Call) RunAndReturn(run func(context.Context, domain.Provider) error) *MockProviderRegistry_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProviderRegistry creates a new instance of MockProviderRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderRegistry {
	mock := &MockProviderRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
