// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/davidbz/calcifer/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockSimilaritySearch is an autogenerated mock type for the SimilaritySearch type
type MockSimilaritySearch struct {
	mock.Mock
}

type MockSimilaritySearch_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSimilaritySearch) EXPECT() *MockSimilaritySearch_Expecter {
	return &MockSimilaritySearch_Expecter{mock: &_m.Mock}
}

// Index provides a mock function with given fields: ctx, key, embedding, data, ttl
func (_m *MockSimilaritySearch) Index(ctx context.Context, key string, embedding []float64, data []byte, ttl time.Duration) error {
	ret := _m.Called(ctx, key, embedding, data, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []float64, []byte, time.Duration) error); ok {
		r0 = rf(ctx, key, embedding, data, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSimilaritySearch_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type MockSimilaritySearch_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - embedding []float64
//   - data []byte
//   - ttl time.Duration
func (_e *MockSimilaritySearch_Expecter) Index(ctx interface{}, key interface{}, embedding interface{}, data interface{}, ttl interface{}) *MockSimilaritySearch_Index_Call {
	return &MockSimilaritySearch_Index_Call{Call: _e.mock.On("Index", ctx, key, embedding, data, ttl)}
}

func (_c *MockSimilaritySearch_Index_Call) Run(run func(ctx context.Context, key string, embedding []float64, data []byte, ttl time.Duration)) *MockSimilaritySearch_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]float64), args[3].([]byte), args[4].(time.Duration))
	})
	return _c
}

func (_c *MockSimilaritySearch_Index_Call) Return(_a0 error) *MockSimilaritySearch_Index_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSimilaritySearch_Index_Call) RunAndReturn(run func(context.Context, string, []float64, []byte, time.Duration) error) *MockSimilaritySearch_Index_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, embedding, threshold, limit
func (_m *MockSimilaritySearch) Search(ctx context.Context, embedding []float64, threshold float64, limit int) ([]*domain.SearchResult, error) {
	ret := _m.Called(ctx, embedding, threshold, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []float64, float64, int) ([]*domain.SearchResult, error)); ok {
		return rf(ctx, embedding, threshold, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []float64, float64, int) []*domain.SearchResult); ok {
		r0 = rf(ctx, embedding, threshold, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []float64, float64, int) error); ok {
		r1 = rf(ctx, embedding, threshold, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSimilaritySearch_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockSimilaritySearch_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - embedding []float64
//   - threshold float64
//   - limit int
func (_e *MockSimilaritySearch_Expecter) Search(ctx interface{}, embedding interface{}, threshold interface{}, limit interface{}) *MockSimilaritySearch_Search_Call {
	return &MockSimilaritySearch_Search_Call{Call: _e.mock.On("Search", ctx, embedding, threshold, limit)}
}

func (_c *MockSimilaritySearch_Search_Call) Run(run func(ctx context.Context, embedding []float64, threshold float64, limit int)) *MockSimilaritySearch_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]float64), args[2].(float64), args[3].(int))
	})
	return _c
}

func (_c *MockSimilaritySearch_Search_Call) Return(_a0 []*domain.SearchResult, _a1 error) *MockSimilaritySearch_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSimilaritySearch_Search_Call) RunAndReturn(run func(context.Context, []float64, float64, int) ([]*domain.SearchResult, error)) *MockSimilaritySearch_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSimilaritySearch creates a new instance of MockSimilaritySearch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSimilaritySearch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSimilaritySearch {
	mock := &MockSimilaritySearch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
